2024-01-06 14:46:41,255 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-06 14:46:41,255 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Configure stats pid to 61646
2024-01-06 14:46:41,255 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Loading settings from /Users/curtispond/.config/wandb/settings
2024-01-06 14:46:41,255 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Loading settings from /Users/curtispond/Documents/wandb/wandb/settings
2024-01-06 14:46:41,255 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-06 14:46:41,255 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-06 14:46:41,256 INFO    MainThread:61646 [wandb_init.py:_log_setup():524] Logging user logs to /Users/curtispond/Documents/wandb/wandb/run-20240106_144641-yn17vvbw/logs/debug.log
2024-01-06 14:46:41,256 INFO    MainThread:61646 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/curtispond/Documents/wandb/wandb/run-20240106_144641-yn17vvbw/logs/debug-internal.log
2024-01-06 14:46:41,256 INFO    MainThread:61646 [wandb_init.py:init():564] calling init triggers
2024-01-06 14:46:41,256 INFO    MainThread:61646 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'learning': 'marketing-analytics', 'task': 'classification'}
2024-01-06 14:46:41,256 INFO    MainThread:61646 [wandb_init.py:init():614] starting backend
2024-01-06 14:46:41,256 INFO    MainThread:61646 [wandb_init.py:init():618] setting up manager
2024-01-06 14:46:41,335 ERROR   MainThread:61646 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 619, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 197, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 37, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
